### PR TITLE
Update event.ts

### PR DESCRIPTION
**Pull request by grmkris**
## Overview

As described here https://openmeter.io/docs/getting-started/event-ingestion#heading-event-format:~:text=The%20data%20property%20can%20contain%20any%20valid%20JSON%20object%2C%20and%20when%20configuring%20meters%20using%20JSONPath%2C%20individual%20values%20can%20be%20extracted Data can be any field, but data type only allowed 2 level deep nesting. My fixes allows any level deep json object

Fixes #(issue)

## Notes for reviewer

Maybe there is some better way to define this

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tothandras** [comment]
Thank you @grmkris! The OpenAPI type generator uses: `{ [key: string]: unknown }`. I'm not sure which one is better, it might be good enough: https://github.com/openmeterio/openmeter/blob/850becce529a707eb3c6b286a5c069b0f35008a2/api/client/node/schemas/openapi.ts#L141

**Comment by grmkris** [comment]
`{ [key: string]: unknown }` is indeed better.. yesterday i had to "copy-paste" your openapi and build my own client, because I use commonjs and your lib doesn't like it for some reason :( 

i noticed that openapi defines `{ [key: string]: unknown }` so internally i already fixed it on my side, but forgot to do it here

**Comment by tothandras** [comment]
Thank you, @grmkris! Please rebase your branch on main, so I can go ahead and merge it. I’ll take a look at commonjs imports.

**Comment by grmkris** [comment]
i don't know how to rebase properly, is a regular merge with dev sufficent? 
if not i'll make a new clean PR tomorrow with just the specific change

**Comment by tothandras** [comment]
I'm allowed to edit your branch, let me do it for you. :)
image

**Comment by tothandras** [comment]
Thank you for your contribution. We'll release it sometime today.

**Pull request merged**
