### PR TITLE
feat: add Licensei

### LINKED ISSUE #22: Add license header to all files
- Add [licensei](https://github.com/goph/licensei) to the tooling and CI to verify headers (example: https://github.com/bank-vaults/vault-secrets-webhook)
- Add license headers to Go files ([addlicense](https://github.com/google/addlicense) can make it easier for the first time)

Copyright holder is `Tailfin Cloud Inc.`.

### PR DESCRIPTION
**Pull request by csatib02**
## Overview

- Connected `Licensei` to the CI.
- Added license-header to all go files.
- Fixed all license-check errors.
- Updated the `readme`.

Fixes #22

### CODE REVIEW

**Review by sagikazarmark — CHANGES_REQUESTED** [review]
Can you please take a look at the failing tests?

**Comment by tothandras** [comment]
@csatib02 Please check the failing test, then break it into two commits, so it's easier to review: 1. configs, readme, etc 2. license headers

**Comment by csatib02** [comment]
I looked into the issue with the sometimes failing e2e-tests, and it is most probably linked to the timing of the events created.
> In my case the e2e-test showed, that the values returned by the query had the values: 1000, and 1000, but 1500 and 500 were expected.
> So 10 events fell into each window.
- The first 5 events are generated at the `initial timestamp`, then `initial timestamp` plus one minute, then plus one hour, and finally plus one day.
- At test `"Day"`, it queries for the sum of events happened in two 24h windows:
1. Starting at the `initial timestamp`
- 3 event generations fall in here: initial, plus one minute, plus one hour.
- A total of 15 events expected.

2. Then at `initial timestamp` + 24 hours
- 1 event is generated at this point: plus one day.
- A total of 5 events expected.

**The reason why it fails sometimes:**
- Despite of the fact that the `initial timestamp` is seeded, it can change when a new dagger engine is hosted. (I added some pictures of logs. I managed to produce a fail aswell. :)
- The `initial timestamp` is close to the end of a 24hour window, so for events generated at `initial timestamp` plus one minute, or one hour, it can end up in the next window.

I can come up with a solution for this in a follow up PR if you want me to do so. 😀
I opened an issue regarding this:

**Pass**
image

**Fail**
image

**Comment by sagikazarmark** [comment]
Can you please rebase?

**Comment by csatib02** [comment]
@sagikazarmark Done.

**Comment by GAlexIHU** [comment]
Closing due to inactivity

**Comment by csatib02** [comment]
Hey @GAlexIHU,

This PR was opened nearly a year ago...
Despite my best efforts, I barely even got a response on it, although i rebased it like a 100 times. :D

I would still finish-up this one, it depends whether you are interested in it.

**Comment by GAlexIHU** [comment]
Hey @csatib02, thanks for the continued interest in contributing! 

I'm personally not sure what the current take is on Licensei integration / source bleeding, probably @tothandras or @turip has more insight on this

**Pull request closed without merging**
