### PR TITLE
feat(config): add auth support

### PR DESCRIPTION
**Pull request by hekike**
Support Kafka, KSQL, and Schema Registry authentications.

**Breaking change:**

- `ingest.kafka.schemaRegistry` => `schemaRegistry.url`

### CODE REVIEW

**Comment by hekike** [comment]
Note: config logging needs improvement to avoid logging secrets

**Comment by sagikazarmark** [comment]
Not sure I understand why the schema registry config was moved out of the ingest section. As far as I can see, it's still exclusively used in the kafka ingest collector.

**Comment by hekike** [comment]
Schema registry is a separate service primarily leveraged by the Kafka ecosystem (in this case Kafka client and ksqlDB) but it's technically independent from Kafka and could be used without it, for example: https://docs.aws.amazon.com/glue/latest/dg/schema-registry.html

**Comment by hekike** [comment]
Discussed that schema registry can be more generic in future

**Pull request merged**
